QRCodeGeneratorMVC/Models/DynamicImageModel.cs
using System.ComponentModel.DataAnnotations;

namespace QRCodeGeneratorMVC.Models
{
    public class DynamicImageModel
    {
        [Display(Name = "Enter Text")]
        public string JobTitle { get; set; }
    }
}

QRCodeGeneratorMVC/Models/ErrorViewModel.cs
namespace QRCodeGeneratorMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

QRCodeGeneratorMVC/Models/QRCodeModel.cs
using System.ComponentModel.DataAnnotations;

namespace QRCodeGeneratorMVC.Models
{
    public class QRCodeModel
    {
        [Display(Name = "Enter QRCode Text")]
        public string QRCodeText { get; set; }
    }
}

QRCodeGeneratorMVC/Controllers/DynamicImageController.cs
using Microsoft.AspNetCore.Mvc;
using QRCodeGeneratorMVC.Models;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net;

namespace QRCodeGeneratorMVC.Controllers
{
    public class DynamicImageController : Controller
    {
        public IActionResult CreateDynamicImage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateDynamicImage(DynamicImageModel dynamicImage)
        {
            // Background image
            string backgroundImageUrl = "https://userhub.com.bd/wp-content/uploads/2018/08/partner-bd-jobs.png";
            Image backgroundImage = LoadImageFromUrl(backgroundImageUrl);

            // Logo image
            string toplogoImageUrl = "https://thumbs.dreamstime.com/b/tiger-running-holding-box-both-hands-logo-mascot-delivery-vector-illustration-tiger-running-holding-box-both-hands-logo-199419145.jpg";
            Image topLogoImage = LoadImageFromUrl(toplogoImageUrl);
            
            // Logo image
            string logoImageUrl = "https://bdjobs.com/images/logo.png";
            Image logoImage = LoadImageFromUrl(logoImageUrl);
            
            // Logo image
            string qrImageUrl = "https://cdn2.hubspot.net/hubfs/477837/Imported_Blog_Media/QR_Code-1.jpg";
            Image qrImage = LoadImageFromUrl(qrImageUrl);

            // Text
            string text = dynamicImage.JobTitle; //"Software Engineer";
            Font font = new Font("Arial", 30, FontStyle.Bold);
            Brush textBrush = new SolidBrush(Color.Navy);

            int totalWidth = 1000;
            int totalHeight = 600;

            var qrImageHeight = 120;
            var qrImageWidth = 120;
            
            var leftTopImageHeight = 200;
            var leftTopImageWidth = 200;
            
            var leftBottomImageHeight = 100;
            var leftBottomImageWidth = 250;

            // Create a new image with the same dimensions as the background
            using (Bitmap resultImage = new Bitmap(totalWidth, totalHeight))
            {
                using (Graphics graphics = Graphics.FromImage(resultImage))
                {
                    graphics.Clear(Color.White);

                    var padding = 30;

                    // Draw the background image to cover the entire canvas
                    using (ImageAttributes attributes = new ImageAttributes())
                    {
                        // Set the opacity (0.5 for 50% transparency, adjust as needed)
                        attributes.SetColorMatrix(new ColorMatrix { Matrix33 = 0.5f });
                        graphics.DrawImage(backgroundImage, new Rectangle(0, 0, totalWidth, totalHeight),
                            0, 0, backgroundImage.Width, backgroundImage.Height, GraphicsUnit.Pixel, attributes);
                    }

                    // Draw the logo in the left top corner
                    graphics.DrawImage(topLogoImage, new Rectangle(0 + padding, 0 + padding, leftTopImageWidth, leftTopImageHeight));
                    
                    // Draw the image in the left bottom corner
                    graphics.DrawImage(logoImage, new Rectangle(0 + padding, totalHeight - leftBottomImageHeight - padding, leftBottomImageWidth, leftBottomImageHeight));
                    
                    // Draw the image in the right bottom corner
                    graphics.DrawImage(qrImage, new Rectangle(totalWidth - qrImageWidth - padding, totalHeight - qrImageHeight - padding, qrImageWidth, qrImageHeight));

                    // Draw the text in the right top corner
                    SizeF textSize = graphics.MeasureString(text, font);
                    float textX = resultImage.Width - textSize.Width - padding; 
                    float textY = 100; //Top Padding
                    graphics.DrawString(text, font, textBrush, new PointF(textX, textY));
                }

                // Save the result image to a file or stream
                //resultImage.Save("output.jpg", ImageFormat.Jpeg);

                string base64Image = ConvertImageToBase64(resultImage);
                ViewBag.dynamicImage = base64Image;                
            }
            return View();
        }

        static Image LoadImageFromUrl(string url)
        {
            using (WebClient webClient = new WebClient())
            {
                byte[] data = webClient.DownloadData(url);
                using (MemoryStream stream = new MemoryStream(data))
                {
                    return Image.FromStream(stream);
                }
            }
        }

        static string ConvertImageToBase64(Image image)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                // Save the image to the memory stream
                image.Save(ms, ImageFormat.Jpeg);

                // Convert the byte array to Base64
                byte[] imageBytes = ms.ToArray();

                return string.Format("data:image/png;base64,{0}", Convert.ToBase64String(imageBytes));
                //return Convert.ToBase64String(imageBytes);
            }
        }
    }
}

QRCodeGeneratorMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QRCodeGeneratorMVC.Models;
using System.Diagnostics;

namespace QRCodeGeneratorMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

QRCodeGeneratorMVC/Controllers/QRCodeController.cs
using Microsoft.AspNetCore.Mvc;
using QRCodeGeneratorMVC.Models;
using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;

namespace QRCodeGeneratorMVC.Controllers
{
    public class QRCodeController : Controller
    {
        public IActionResult CreateQRCode()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateQRCode(QRCodeModel qRCode)
        {
            QRCodeGenerator QrGenerator = new QRCodeGenerator();
            QRCodeData QrCodeInfo = QrGenerator.CreateQrCode(qRCode.QRCodeText, QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(QrCodeInfo);
            Bitmap QrBitmap = qrCode.GetGraphic(60);

            byte[] BitmapArray;
            using (MemoryStream ms = new MemoryStream())
            {
                QrBitmap.Save(ms, ImageFormat.Png);
                BitmapArray =  ms.ToArray();
            }

            string QrUri = string.Format("data:image/png;base64,{0}", Convert.ToBase64String(BitmapArray));
            ViewBag.QrCodeUri = QrUri;
            return View();
        }

        
    }
}

QRCodeGeneratorMVC/Views/DynamicImage/CreateDynamicImage.cshtml
@model QRCodeGeneratorMVC.Models.DynamicImageModel

@{
    ViewData["Title"] = "View";
}

<h4>DynamicImageModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateDynamicImage" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JobTitle" class="control-label"></label>
                <input asp-for="JobTitle" class="form-control" />
                <span asp-validation-for="JobTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div class="form-group"> 
                <img src="@ViewBag.dynamicImage" width="1000" height="800" class="img-thumbnail" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QRCodeGeneratorMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

QRCodeGeneratorMVC/Views/QRCode/CreateQRCode.cshtml
@model QRCodeGeneratorMVC.Models.QRCodeModel

@{
    ViewData["Title"] = "QRCode";
}

<h1>QRCode</h1>

<h4>QRCodeModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateQRCode" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="QRCodeText" class="control-label"></label>
                <input asp-for="QRCodeText" class="form-control" />
                <span asp-validation-for="QRCodeText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div class="form-group">

                <img src="@ViewBag.QrCodeUri" class="img-thumbnail" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QRCodeGeneratorMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QRCodeGeneratorMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QRCodeGeneratorMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QRCodeGeneratorMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="QRCode" asp-action="CreateQRCode">Create QRCode</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DynamicImage" asp-action="CreateDynamicImage">Create Image</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - QRCodeGeneratorMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>